### ISSUE TITLE
About Entity Clustering Labels

### ISSUE THREAD

**Issue by kimwongyuda** [JiachengLi1995/UCTopic#4]
First, thank you for presenting the nice paper.

When reading your paper, I wondered the below question.

When you evaluate in terms of Entity Clustering, how did you construct the label for each entity?

1) The datasets have the label for each entity itself?
or
2) Did you use pseudo labels as the labels?
or
3) The kinds of entities were used for the labels?

Thank you!

**Comment by JiachengLi1995** [comment]
We are using the NER datasets for entity clustering so all entities are annotated in these datasets including the types and positions of entities. In our clustering, we assume the positions of entities are known and conduct clustering on the types of entities.

**Comment by kimwongyuda** [comment]
Thank you so much for replying !!!
